name: Run Animenosub

on:
  workflow_dispatch:

jobs:
  run-animenosub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run Animenosub Script
        run: python private_py/anime/ingilizce/animenosub/animenosubjson.py

      - name: Commit and Push JSON to Public Repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add animenosub/*.json || echo "No JSON files"
          git commit -m "Animenosub JSON güncellendi [auto]" || echo "No changes"
          git push origin main
