name: Push All M3U Playlists to m3u8file Repo Root

on:
  workflow_dispatch:
  schedule:
    - cron: '20 */11 * * *'

jobs:
  push-m3u-to-root:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout this public repo
        uses: actions/checkout@v4

      - name: Checkout private Python repo (birlestirtoken2.py)
        uses: actions/checkout@v4
        with:
          repository: zerodayip/Py
          token: ${{ secrets.GH_TOKEN }}
          path: private_py
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Run birleştirici / üretici scriptleri
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python private_py/series/birlestirtoken2.py
