name: Run Xtream Json Maker

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run Xtream M3U Maker"]
    types:
      - completed

jobs:
  run-xtream:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout Public Repo (Genel repo)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Run Xtream Script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python private_py/xtream/convert.py

      # === GENEL REPOYA times.json PUSH ===
      - name: Commit and Push times.json to General Repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add xtream/times.json || echo "No times.json"
          git commit -m "times.json güncellendi [auto]" || echo "No changes"
          git pull --rebase origin main || echo "No upstream changes"
          git push origin main || echo "No push needed"

      # === m3u8file REPOSU ===
      - name: Clone m3u8file Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/m3u8file.git m3u8file_repo

      - name: Copy only JSON files (excluding times.json) to m3u8file/xtreamjson
        run: |
          mkdir -p m3u8file_repo/xtreamjson
          find xtream -name "*.json" ! -name "times.json" -exec cp {} m3u8file_repo/xtreamjson/ \;

      - name: Commit and Push to m3u8file/xtreamjson
        run: |
          cd m3u8file_repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add xtreamjson/*.json || echo "No JSON files to add"
          git commit -m "Xtream JSON dosyaları xtreamjson klasörüne eklendi [auto]" || echo "No changes"
          git pull --rebase origin main || echo "No upstream changes"
          git push origin main || echo "No push needed"
