name: Py'den SezonlukDizi Köke Kopya

on:
  workflow_dispatch:

jobs:
  copy-to-root:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Clone SezonlukDizi Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/sezonlukdizi.git private_sezonlukdizi

      - name: Copy m3u8sezonlukdizi içeriğini köke taşı
        run: |
          rsync -a private_py/m3u8sezonlukdizi/ private_sezonlukdizi/

      - name: Commit and Push to SezonlukDizi Repo
        run: |
          cd private_sezonlukdizi
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add . || echo "No files"
          git commit -m "m3u8sezonlukdizi içeriği Py'den köke taşındı [auto]" || echo "No changes"
          git push origin main
