name: Run TurkAnime Script JSON

on:
  workflow_dispatch:

jobs:
  run-sezonlukdizi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo (sitem3u)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install playwright beautifulsoup4
          playwright install

      - name: Run TurkAnime Script
        run: python private_py/turkanime/turkanime.py

      - name: Commit and Push to Public Repo (sitem3u)
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add debug.html anime/**/*.m3u anime/animeler.json || echo "No files"
          git commit -m "SezonlukDizi güncellendi [auto]" || echo "No changes"
          git push origin main

      - name: Copy updated M3U folders to private repo (with structure)
        run: |
          mkdir -p private_py/m3u8/sezonlukdizi
          rsync -a anime/ private_py/m3u8/sezonlukdizi/

      - name: Push to Private Py Repo
        run: |
          cd private_py
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add m3u8/sezonlukdizi/**/*.m3u || echo "No M3U to add"
          git commit -m "SezonlukDizi çıktı güncellendi [auto]" || echo "No changes"
          git push origin main
