name: Run SezonlukDizi Script JSON

on:
  workflow_dispatch:

jobs:
  run-sezonlukdizi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo (sitem3u)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run SezonlukDizi Script (No Playwright)
        run: python private_py/sezonlukdizi/dizi.py

      - name: Commit and Push to Public Repo (sitem3u)
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sdizi/*.m3u
          git commit -m "SezonlukDizi güncellendi [auto]" || echo "No changes"
          git push origin main

      - name: Copy files to private_py/m3u8/sezonlukdizi
        run: |
          mkdir -p private_py/m3u8/sezonlukdizi
          cp sdizi/*.m3u private_py/m3u8/sezonlukdizi/ || echo "m3u dosyaları kopyalanamadı"

      - name: Push to Private Py Repo
        run: |
          cd private_py
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add m3u8/sezonlukdizi/*.m3u
          git commit -m "SezonlukDizi çıktıları güncellendi [auto]" || echo "No changes"
          git push origin main
