name: Run Dizigom m3u Bölüm Takip

on:
  workflow_dispatch:
  push:
    paths:
      - 'dizigom/yenibolumler.json' 

jobs:
  run-dizigom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 lxml playwright
          playwright install

      - name: Run Dizigom Script
        run: python private_py/series/dizigom/yenibolumler.py

      ############################################################
      # ÇIKTILARI PRIVATE_DIZIGOM REPO'SUNA KOPYALA ve PUSH'LA
      ############################################################

      - name: Clone Private Dizigom Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/private_dizigom.git private_dizigom

      - name: Copy M3U and JSON to Private Dizigom Repo
        run: |
          rsync -a dizigom/ private_dizigom/

      - name: Commit and Push to Private Dizigom Repo
        run: |
          cd private_dizigom
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add . || echo "No files"
          git commit -m "Dizigom çıktı güncellendi [auto]" || echo "No changes"
          git push origin main
