name: M3U MAKER D

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # Her 5 saatte bir

jobs:
  ##################################
  # PART 1 - JSONLARI OLUŞTUR
  ##################################
  part1:
    name: Step 1-2-3 Çalıştır
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout public repo (main)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: main

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-cache-${{ runner.os }}-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Shared Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml playwright aiohttp aiofiles dotenv
          playwright install

      # 1. IPTV ve Dizi Çıktıları
      - name: Run IPTV & Dizi Scripts
        run: |
          python private_py/vavoo/iptv/vavooiptvkendi.py
          python private_py/series/dizifun/yenibolumler.py
          python private_py/series/dizilife/yenibolumler.py

      - name: Sync Vavoo outputs to private m3u8file repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/m3u8file.git private_m3u8file
          cp v/vavoo.m3u private_m3u8file/vavoo.m3u || echo "vavoo.m3u yok"
          cp dizifundizi.m3u private_m3u8file/dizifundizi.m3u || echo "dizifundizi.m3u yok"
          cp dizilifedizi.m3u private_m3u8file/dizilifedizi.m3u || echo "dizilifedizi.m3u yok"
          cd private_m3u8file
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Vavoo & DiziFun & DiziLife çıktısı güncellendi [auto]" || echo "No changes"
          git push origin main

      # 2. JSON Çıktıları
      - name: Run All JSON Scripts
        run: |
          python private_py/series/dizigom/dizigomdizijson.py
          python private_py/series/sezonlukdizi/tumdizilerjson.py
          python private_py/anime/anizm/anizimjson.py
          python private_py/anime/ingilizce/animenosub/animenosubjson.py
          python private_py/series/setfilmizledizi/setfilmizledizijson.py

      - name: Commit and Push All JSONs
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dizigom/*.json sdizi/*.json anizm/*.json animenosub/*.json setfilmizledizi/*.json || echo "No files"
          git commit -m "All JSON güncellendi [auto]" || echo "No changes"
          git push origin main

  ##################################
  # PART 2 - PARALEL İŞLER
  ##################################
  sezonlukdizi:
    name: 4️⃣ SezonlukDizi M3U Maker
    runs-on: ubuntu-latest
    needs: part1
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py
      - run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml aiohttp aiofiles dotenv
      - run: python private_py/series/sezonlukdizi/yenibolumler.py
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sdizi/*.json || echo "No JSON files"
          git commit -m "SezonlukDizi JSON güncellendi [auto]" || echo "No changes"
          git push origin main

  dizigom:
    name: 5️⃣ Dizigom M3U Maker
    runs-on: ubuntu-latest
    needs: part1
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py
      - run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml aiohttp aiofiles dotenv
      - run: python private_py/series/dizigom/yenibolumler.py
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dizigom/*.json || echo "No JSON files"
          git commit -m "Dizigom JSON güncellendi [auto]" || echo "No changes"
          git push origin main

  anizm:
    name: 6️⃣ Anizm M3U Maker
    runs-on: ubuntu-latest
    needs: part1
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py
      - run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml aiohttp aiofiles dotenv
      - run: python private_py/anime/anizm/yenibolumler.py
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add anizm/*.json || echo "No JSON files"
          git commit -m "Anizm JSON güncellendi [auto]" || echo "No changes"
          git push origin main

  animenosub:
    name: 8️⃣ AnimeNoSub M3U Maker
    runs-on: ubuntu-latest
    needs: part1
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py
      - run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml aiohttp aiofiles dotenv
      - run: python private_py/anime/ingilizce/animenosub/yenibolumler.py
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add animenosub/*.json || echo "No JSON files"
          git commit -m "AnimeNoSub JSON güncellendi [auto]" || echo "No changes"
          git push origin main

  setfilmizledizi:
    name: 9️⃣ SetFilmİzleDizi M3U Maker
    runs-on: ubuntu-latest
    needs: part1
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py
      - run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml aiohttp aiofiles dotenv
      - run: python private_py/series/setfilmizledizi/yenibolumler.py
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add setfilmizledizi/*.json || echo "No JSON files"
          git commit -m "SetFilmİzleDizi JSON güncellendi [auto]" || echo "No changes"
          git push origin main

  ##################################
  # PART 3 - ANA JSON OLUŞTUR (Tüm part2 işler bitince)
  ##################################
  ana_json:
    name: 🔟 Yeni JSON'dan Ana JSON oluştur
    runs-on: ubuntu-latest
    needs: [sezonlukdizi, dizigom, anizm, animenosub, setfilmizledizi]
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py
      - run: python private_py/series/yenibolumdenanajsona.py
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dizigom/*.json sdizi/*.json anizm/*.json animenosub/*.json setfilmizledizi/*.json || echo "No files"
          git commit -m "All Ana JSON güncellendi [auto]" || echo "No changes"
          git push origin main

  ##################################
  # PART 4 - FİLMLER
  ##################################
  filmler:
    name: 🎬 Filmler İşlemleri
    runs-on: ubuntu-latest
    needs: ana_json
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py
      - run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml aiohttp aiofiles dotenv
      - run: |
          python private_py/movies/dizigom/dizigomfilmler.py
          python private_py/movies/setfilmizle/ilksayfatümm3uolusturma.py
      - run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/m3u8file.git private_m3u8file
          cp dizigomfilmler.m3u private_m3u8file/dizigomfilmler.m3u || echo "dizigomfilmler.m3u yok"
          cp xtream/setfilmizlefilmler.m3u private_m3u8file/setfilmizlefilmler.m3u || echo "setfilmizlefilmler.m3u yok"
          cd private_m3u8file
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add setfilmizlefilmler.m3u dizigomfilmler.m3u
          git commit -m "Filmlerin çıktısı güncellendi [auto]" || echo "No changes"
          git push origin main
