name: Run SezonlukDizi Yıla Göre Dizi Takip JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '* */4 * * *'
jobs:
  run-sezonlukdizi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo (sitem3u)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run SezonlukDizi Script
        run: python private_py/sezonlukdizi/yilagore.py

      - name: Commit and Push to Public Repo (sitem3u)
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sdizi/*.json || echo "No files"
          git commit -m "SezonlukDizi JSON güncellendi [auto]" || echo "No changes"
          git push origin main
