name: Kopyala

on:
  workflow_dispatch:

jobs:
  run-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo (sitem3u)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Copy updated M3U folders to private repo (with structure)
        run: |
          mkdir -p private_py/m3u8sezonlukdizi
          rsync -a sdizi/ private_py/m3u8sezonlukdizi/

      - name: Push to Private Py Repo
        run: |
          cd private_py
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add m3u8sezonlukdizi/**/*.m3u || echo "No M3U to add"
          git commit -m "SezonlukDizi çıktı güncellendi [auto]" || echo "No changes"
          git push origin main
