name: Push to Private Py Repo

on:
  workflow_dispatch:
  push:
    paths:
      - 'yenibolumler.json'

jobs:
  push-private-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Copy updated M3U folders to private repo (with structure)
        run: |
          mkdir -p private_py/m3u8sezonlukdizi
          rsync -a sdizi/ private_py/m3u8sezonlukdizi/

      - name: Push to Private Py Repo
        run: |
          cd private_py
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add m3u8sezonlukdizi/**/*.m3u || echo "No M3U to add"
          git commit -m "SezonlukDizi çıktı güncellendi [auto]" || echo "No changes"
          git push origin main
