name: Push All M3U Playlists to m3u8file Repo Root

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */10 * * *'

jobs:
  push-m3u-to-root:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN1: ${{ secrets.GH_TOKEN1 }}
      GH_TOKEN2: ${{ secrets.GH_TOKEN2 }}
      GH_TOKEN3: ${{ secrets.GH_TOKEN3 }}
      GH_TOKEN4: ${{ secrets.GH_TOKEN4 }}
      GH_TOKEN5: ${{ secrets.GH_TOKEN5 }}

    steps:
      - name: Checkout public repo (bu workflow'un olduğu repo)
        uses: actions/checkout@v4

      - name: Checkout private_py repo
        uses: actions/checkout@v4
        with:
          repository: zerodayip/Py
          token: ${{ secrets.GH_TOKEN1 }}
          path: private_py
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Run birleştirici / üretici scriptleri
        env:
          GH_TOKEN1: ${{ secrets.GH_TOKEN1 }}
          GH_TOKEN2: ${{ secrets.GH_TOKEN2 }}
          GH_TOKEN3: ${{ secrets.GH_TOKEN3 }}
          GH_TOKEN4: ${{ secrets.GH_TOKEN4 }}
          GH_TOKEN5: ${{ secrets.GH_TOKEN5 }}
        run: |
          python private_py/series/birlestirtoken.py

      - name: Checkout private m3u8file repo
        uses: actions/checkout@v4
        with:
          repository: zerodayip/m3u8file
          token: ${{ secrets.GH_TOKEN1 }}
          path: private_m3u8file
          fetch-depth: 0

      - name: Copy all M3U files to root of m3u8file repo
        run: |
          find . -maxdepth 2 -type f -name "*.m3u" -exec cp {} private_m3u8file/ \;

      - name: Commit and push M3U files
        run: |
          cd private_m3u8file
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add *.m3u || echo "No M3U to add"
          git commit -m "Tüm M3U dosyaları güncellendi [auto]" || echo "No changes to commit"
          # Remote URL'yi PAT ile tekrar ayarla (push için)
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN1 }}@github.com/zerodayip/m3u8file.git
          git push origin main

