name: Push

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run m3u takip"]
    types:
      - completed

jobs:
  merge-m3u-playlists:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python dependencies
        run: |
          pip install requests

      - name: Merge M3U Playlists
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python private_py/series/sezonlukdizi/birlestir.py

      - name: Configure Git for Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Only sezonlukdizi.m3u
        run: |
          git add ./sezonlukdizi.m3u
          git diff --cached --quiet || (git commit -m "Update sezonlukdizi.m3u via GitHub Actions" && git push)

  sync-root-folder:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    needs: merge-m3u-playlists

    steps:
      - name: Wait 30 seconds before starting the sync process
        run: |
          echo "Waiting for 30 seconds before starting..."
          sleep 30

      - name: Checkout Public Repository (sitem3u)
        uses: actions/checkout@v4
        with:
          repository: 'zerodayip/seriesmovies'
          token: ${{ secrets.GH_TOKEN }}
          ref: main

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Copy ONLY sezonlukdizi.m3u to m3u8 folder in Private Py Repo
        run: |
          mkdir -p private_py/m3u8
          cp sezonlukdizi.m3u private_py/m3u8/

      - name: Check if sezonlukdizi.m3u is copied
        run: |
          echo "Files in m3u8 folder:"
          ls private_py/m3u8

      - name: Configure Git for Commit (Again)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push ONLY sezonlukdizi.m3u to Private Py Repo
        run: |
          cd private_py
          git add m3u8/sezonlukdizi.m3u
          git diff --cached --quiet || git commit -m "Sync sezonlukdizi.m3u into m3u8 folder [auto]"
          git push origin main

      - name: Create or Update sil.txt (Trigger file)
        run: |
          echo "This is a trigger file $(date)" > sil.txt
          git add sil.txt
          git commit -m "Trigger to Next Step"
          git push origin main
