name: Push All M3U Playlists to m3u8file Repo Root

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run RecTV Script and Push to m3u8file/rec"]
    types:
      - completed

jobs:
  push-m3u-to-root:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout (public kod)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      # Scriptlerini burada çalıştırabilirsin
      - name: Birleştirici / Üretici scriptleri çalıştır
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python private_py/series/birlestir.py


      - name: Clone Private m3u8file Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/m3u8file.git private_m3u8file

      # Tüm m3u dosyalarını ana dizine kopyala
      - name: Copy all M3U files to root of m3u8file repo
        run: |
          find . -maxdepth 2 -type f -name "*.m3u" -exec cp {} private_m3u8file/ \;

      - name: Commit and Push all M3U to m3u8file Repo
        run: |
          cd private_m3u8file
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add *.m3u || echo "No M3U to add"
          git commit -m "Tüm M3U dosyaları güncellendi [auto]" || echo "No changes"
          git push origin main
