name: Run All JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # Her 12 saatte bir

jobs:
  run-make-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo (sitem3u)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python Dependencies (requests, bs4, lxml, playwright)
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 lxml playwright
          playwright install

#      - name: Run Dizigom Script
#        run: python private_py/series/dizigom/dizigomdizijson.py

#      - name: Run Sezonlukdizi Script
#        run: python private_py/series/sezonlukdizi/tumdizilerjson.py

#      - name: Run Anizm Script
#        run: python private_py/anime/anizm/anizimjson.py

      - name: Run AnimeIzlesene Script
        run: python private_py/anime/animeizlesene/animeizlesenejson.py

      - name: Commit and Push JSONs
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          git add dizigom/*.json || echo "No dizigom files"
          git add sdizi/*.json || echo "No sezonlukdizi files"
          git add anizm/*.json || echo "No anizm files"
          git add animeizlesene/*.json || echo "No animeizlesene files"

          git commit -m "All JSON güncellendi [auto]" || echo "No changes"
          git push origin main
