name: Run SezonlukDizi & Dizigom m3u Bölüm Takip

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run Dizigom ve Sezonlukdizi JSON"]
    types:
      - completed
  
jobs:
  run-sezonlukdizi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run SezonlukDizi Script
        run: python private_py/series/sezonlukdizi/yenibolumler.py

      - name: Commit and Push JSON to Public Repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sdizi/*.json || echo "No JSON files"
          git commit -m "SezonlukDizi JSON güncellendi [auto]" || echo "No changes"
          git push origin main

      - name: Clone Private SezonlukDizi Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/sezonlukdizi.git private_sezonlukdizi

      - name: Copy All to Private SezonlukDizi Repo
        run: |
          rsync -a sdizi/ private_sezonlukdizi/

      - name: Commit and Push All Files to Private SezonlukDizi Repo
        run: |
          cd private_sezonlukdizi
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add . || echo "No files"
          git commit -m "SezonlukDizi çıktı güncellendi [auto]" || echo "No changes"
          git push origin main

  run-dizigom:
    needs: run-sezonlukdizi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 lxml playwright
          playwright install

      - name: Run Dizigom Script
        run: python private_py/series/dizigom/yenibolumler.py

      - name: Commit and Push JSON to Public Repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dizigom/*.json || echo "No JSON files"
          git commit -m "Dizigom JSON güncellendi [auto]" || echo "No changes"
          git push origin main

      - name: Clone Private Dizigom Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/dizigom.git private_dizigom

      - name: Copy All to Private Dizigom Repo
        run: |
          rsync -a dizigom/ private_dizigom/

      - name: Commit and Push All Files to Private Dizigom Repo
        run: |
          cd private_dizigom
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add . || echo "No files"
          git commit -m "Dizigom çıktı güncellendi [auto]" || echo "No changes"
          git push origin main
