name: Get Embed Link

on:
  workflow_dispatch:

jobs:
  get-embed-link:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install playwright requests beautifulsoup4
          playwright install chromium

      - name: Run get_embed.py from private repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python private_py/movies/setfilmizle/tumfilmler.py

      - name: Commit & Push updated m3u to public repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add setfilmizlefilm.m3u || echo "No file"
          git commit -m "✅ setfilmizlefilm.m3u otomatik güncellendi [auto]" || echo "No changes"
          git push origin main

      - name: Copy updated M3U file back to private repo (if needed)
        run: |
          mkdir -p private_py/xtream
          cp setfilmizlefilm.m3u private_py/xtream/

      - name: Commit & Push updated m3u to private repo
        run: |
          cd private_py
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main || echo "No upstream changes"
          git add xtream/setfilmizlefilm.m3u || echo "No M3U to add"
          git commit -m "setfilmizlefilm.m3u güncellendi [auto]" || echo "No changes"
          git push origin main
