name: Run SetFilmIzle Dizi Embed

on:
  workflow_dispatch:

jobs:
  run-setfilmdizi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run SetFilmIzle Dizi Script
        run: python private_py/series/setfilmizle/dizi.py

      - name: Commit and Push to Public Repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add setfilm/*.m3u || echo "No files"
          git commit -m "SezonlukDizi güncellendi [auto]" || echo "No changes"
          git push origin main

      - name: Copy updated M3U folders to private repo (with structure)
        run: |
          mkdir -p private_py/m3u8setfilmizle
          rsync -a setfilm/ private_py/m3u8setfilmizle/

      - name: Push to Private Py Repo
        run: |
          cd private_py
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main || echo "No upstream changes"
          git add m3u8setfilmizle/*.m3u || echo "No M3U to add"
          git commit -m "Setfilmizle çıktı güncellendi [auto]" || echo "No changes"
          git push origin main
