name: Run SezonlukDizi m3u Bölüm Takip

on:
  workflow_dispatch:
  push:
    paths:
      - 'sdizi/yenibolumler.json' 

jobs:
  run-sezonlukdizi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run SezonlukDizi Script
        run: python private_py/series/sezonlukdizi/yenibolumler.py

      ######################
      # 1) PUBLIC REPO'YA SADECE JSON PUSH
      ######################
      - name: Commit and Push JSON to Public Repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sdizi/*.json || echo "No JSON files"
          git commit -m "SezonlukDizi JSON güncellendi [auto]" || echo "No changes"
          git push origin main

      ######################
      # 2) PRIVATE_SEZONLUKDIZI REPO'YA TÜM DOSYALARI PUSH
      ######################
      - name: Clone Private SezonlukDizi Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/sezonlukdizi.git private_sezonlukdizi

      - name: Copy All to Private SezonlukDizi Repo
        run: |
          rsync -a sdizi/ private_sezonlukdizi/

      - name: Commit and Push All Files to Private SezonlukDizi Repo
        run: |
          cd private_sezonlukdizi
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add . || echo "No files"
          git commit -m "SezonlukDizi çıktı güncellendi [auto]" || echo "No changes"
          git push origin main
