name: Run SezonlukDizi Script 3

on:
  workflow_dispatch:

jobs:
  run-sezonlukdizi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo (sitem3u)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Chromium and Chromedriver via apt
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          echo "✅ Chromium ve Chromedriver kuruldu"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml selenium

      - name: Run SezonlukDizi Script
        env:
          DISPLAY: :99
        run: |
          python private_py/sezonlukdizi/proxy3.py

      - name: Commit and Push to Public Repo (sitem3u)
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sdizi/*.m3u
          git commit -m "SezonlukDizi: public repoda güncellendi [auto]" || echo "No changes"
          git push origin main

      - name: Copy files to private_py/m3u8/sezonlukdizi
        run: |
          mkdir -p private_py/m3u8/sezonlukdizi
          cp sdizi/*.m3u private_py/m3u8/sezonlukdizi/ || echo "m3u dosyaları kopyalanamadı"

      - name: Check copied files
        run: |
          echo "📁 Kopyalanan dosyalar:"
          ls -lh private_py/m3u8/sezonlukdizi

      - name: Commit and Push to Private Py Repo
        run: |
          cd private_py
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add m3u8/sezonlukdizi/*.m3u
          git commit -m "SezonlukDizi çıktıları m3u8/sezonlukdizi klasörüne eklendi [auto]" || echo "No changes"
          git push origin main
