name: Run Xtream M3U Maker 2

on:
  workflow_dispatch:
#  workflow_run:
#    workflows: ["Push All M3U Playlists to m3u8file Repo Root"]
#    types:
#      - completed

jobs:
  run-xtream-m3u:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout Public Repo (bu repodaki kodu çekmek için)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Run Xtream Film Script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python private_py/xtream/film.py

      - name: Run Xtream Dizi Script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python private_py/xtream/series.py

      - name: Clone Private m3u8file Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/m3u8file.git private_m3u8file

      - name: Copy updated M3U files to private m3u8file repo
        run: |
          mkdir -p private_m3u8file/xtream
          rsync -a xtream/ private_m3u8file/xtream/ --include="*.m3u" --exclude="*"

      - name: Commit and Push to Private m3u8file Repo
        run: |
          cd private_m3u8file
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add xtream/*.m3u || echo "No M3U to add"
          git commit -m "Xtream M3U dosyaları güncellendi [auto]" || echo "No changes"
          git push origin main
