name: Run Xtream M3U Maker

on:
  workflow_dispatch:

jobs:
  run-xtream-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Run Xtream Film Script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python private_py/xtream/film.py

  #    - name: Run Xtream Dizi Script
  #      env:
  #        GH_TOKEN: ${{ secrets.GH_TOKEN }}
  #      run: python private_py/xtream/dizi.py

      - name: Commit and Push to Public Repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add xtream/*.m3u || echo "No files"
          git commit -m "Xtream M3U güncellendi [auto]" || echo "No changes"
          git push origin main

      - name: Copy updated M3U files to private repo (xtream)
        run: |
          mkdir -p private_py/xtream
          rsync -a xtream/ private_py/xtream/ --include="*.m3u" --exclude="*"

      - name: Push xtream JSONs to Private Py Repo
        run: |
          cd private_py
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main || echo "No upstream changes"
          git add xtream/*.m3u || echo "No M3U to add"
          git commit -m "Xtream M3U dosyaları güncellendi [auto]" || echo "No changes"
          git push origin main
